# NAME: Your Twitch Bot Nickname
# OAUTH: Your OAuth Password
# CHANNEL: Join Channel ID
# MESSAGE: Your Message
# LIMIT: Limitation of messages per joining

NAME: "deditor"
OAUTH: "oauth:youroauthcode"
CHANNEL: "deditor"
MESSAGE: "[찰떡] {}님, 환영합니다!"
LIMIT: 3