# NAME: Your Twitch Bot Nickname
# OAUTH: Your OAuth Password
# CHANNEL: Join Channel ID
# MESSAGE: Your Message
# LIMIT: Limitation of messages per joining

NAME: "dogebot"
OAUTH: "oauth:wfqpxgpk57oeujpag1kqbqy4cf8nvk"
CHANNEL: "DDoDoyaji"
MESSAGE: "[개떡] {}님, 환영합니다!"
LIMIT: 3
