# NAME: Your Twitch Bot Nickname
# OAUTH: Your OAuth Password
# CHANNEL: Join Channel ID
# MESSAGE: Your Message
# LIMIT: Limitation of messages per joining

NAME: "ricebot"
OAUTH: "oauth:123456789abcdef"
CHANNEL: "xqcow"
MESSAGE: "[찰떡] {}님, 환영합니다!"
LIMIT: 3